.DEFAULT: help
help:
    @echo "make prepare-dev"
    @echo "       prepare development environment, use only once."

prepare-dev:
    sudo apt-get -y install python3.6 python3-pip
    python -m venv venv
    pip install -r requirements.txt